### ISSUE TITLE
Issue with Login and pasword

### ISSUE THREAD

**Issue by jeanfrancis** [lifen-labs/covid#12]
when using the heroku Deploy button have an issue to acccess the admin part using login : admin@example.com / password

Cannot connect and have the message : translation missing: fr.devise.failure.admin_user.not_found_in_database

**Comment by mickaeltr** [comment]
Hello @jeanfrancis,
That can be fixed with:
1. https://github.com/mickaeltr/covid/commit/4d7176eaf0dd5d7272ad235d20ef2548078e86c5
2. https://github.com/lifen-labs/covid/pull/7/commits/1232c4931f0e75d2247ad346ba3409a2523af734

**Comment by jeanfrancis** [comment]
Have tried with both changes and same cannot connect to the admin pannel 
Even tried to add more admin users , same

**Comment by jeanfrancis** [comment]
Fixed ! have forget the db:seed command
